/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scissorpaperrock;

import javax.swing.ImageIcon;

/**
 *
 * @author ADmiN
 */
public class ScissorPaperRock extends javax.swing.JFrame {

    int score1 = 1, score2 = 1;

    /**
     * Creates new form ScissorPaperRock
     */
    public ScissorPaperRock() {
        initComponents();
        lblScore1.setText("0");
        lblScore2.setText("0");
        btnReset.setVisible(false);
    }
    
    public void setFalse(){
        if (score1 > 5) {
            lblResult.setText("You won");
            btnScissor.setEnabled(false);
            btnPaper.setEnabled(false);
            btnRock.setEnabled(false);
            btnReset.setVisible(true);
        } else if (score2 > 5) {
            lblResult.setText("The computer won");
            btnScissor.setEnabled(false);
            btnPaper.setEnabled(false);
            btnRock.setEnabled(false);
            btnReset.setVisible(true);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnScissor = new javax.swing.JButton();
        btnPaper = new javax.swing.JButton();
        btnRock = new javax.swing.JButton();
        lblScore1 = new javax.swing.JLabel();
        lblScore2 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblOrdinateur = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 15, 15));

        btnScissor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnScissor.setText("Scissor");
        btnScissor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorActionPerformed(evt);
            }
        });
        jPanel3.add(btnScissor);

        btnPaper.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPaper.setText("Paper");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });
        jPanel3.add(btnPaper);

        btnRock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRock.setText("Rock");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });
        jPanel3.add(btnRock);

        lblScore1.setBackground(new java.awt.Color(102, 255, 255));
        lblScore1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblScore1.setForeground(new java.awt.Color(153, 0, 51));
        lblScore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore1.setOpaque(true);

        lblScore2.setBackground(new java.awt.Color(102, 255, 255));
        lblScore2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblScore2.setForeground(new java.awt.Color(153, 0, 51));
        lblScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore2.setOpaque(true);

        lblResult.setBackground(new java.awt.Color(255, 255, 0));
        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblResult.setForeground(new java.awt.Color(0, 0, 0));
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResult.setOpaque(true);

        lblPlayer.setBackground(new java.awt.Color(255, 255, 255));
        lblPlayer.setOpaque(true);

        lblOrdinateur.setBackground(new java.awt.Color(255, 255, 255));
        lblOrdinateur.setOpaque(true);

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setText("play again");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(lblOrdinateur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrdinateur, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnScissorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorActionPerformed

        lblPlayer.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\SCISSOR.png"));
        double num = Math.random() * 4;
        while ((int) num == 0) {
            num = Math.random() * 4;
        }

        if ((int) num == 1) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\SCISSOR.png"));
        } else if ((int) num == 2) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\PAPER.png"));
        } else if ((int) num == 3) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\ROCK.png"));
        }

        
        int a = 1;
        int b = (int) num;
        
        if(a==1 && b==2){
         lblScore1.setText(String.valueOf(score1++));   
        }else if(a==1 && b==3){
            lblScore2.setText(String.valueOf(score2++));
        }else if(a==1 && b==1){
            lblScore1.setText(lblScore1.getText());
            lblScore2.setText(lblScore2.getText());
        }
        
        
        setFalse();


    }//GEN-LAST:event_btnScissorActionPerformed

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        lblPlayer.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\PAPER.png"));
        double num = Math.random() * 4;
        while ((int) num == 0) {
            num = Math.random() * 4;
        }

        if ((int) num == 1) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\SCISSOR.png"));
        } else if ((int) num == 2) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\PAPER.png"));
        } else if ((int) num == 3) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\ROCK.png"));
        }

        int a = 2;
        int b = (int) num;
        
        
        if(a==2 && b==1){
            lblScore2.setText(String.valueOf(score2++));
        }else if(a==2 && b==3){
            lblScore1.setText(String.valueOf(score1++));
        }else if(a==2 && b==2){
            lblScore1.setText(lblScore1.getText());
            lblScore2.setText(lblScore2.getText());
        }
        
        
        setFalse();


    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        lblPlayer.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\ROCK.png"));
        double num = Math.random() * 4;
        while ((int) num == 0) {
            num = Math.random() * 4;
        }

        if ((int) num == 1) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\SCISSOR.png"));
        } else if ((int) num == 2) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\PAPER.png"));
        } else if ((int) num == 3) {
            lblOrdinateur.setIcon(new ImageIcon("D:\\NetBeans-Java\\ScissorPaperRock\\src\\scissorpaperrock\\game\\ROCK.png"));
        }

        int a = 3;
        int b = (int) num;
        
        
        if(a==3 && b==1){
            lblScore1.setText(String.valueOf(score1++));
        }else if(a==3 && b==2){
            lblScore2.setText(String.valueOf(score2++));
        }else if(a==3 && b==3){
            lblScore1.setText(lblScore1.getText());
            lblScore2.setText(lblScore2.getText());
        }
        
        
        setFalse();

    }//GEN-LAST:event_btnRockActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        lblScore1.setText("");
        lblScore2.setText("");
        lblPlayer.setText("");
        lblOrdinateur.setText("");
        btnScissor.setEnabled(true);
        btnPaper.setEnabled(true);
        btnRock.setEnabled(true);
        btnReset.setVisible(false);
        score1=1;
        score2=1;
        lblScore1.setText("0");
        lblScore2.setText("0");
        lblResult.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScissorPaperRock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScissorPaperRock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScissorPaperRock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScissorPaperRock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScissorPaperRock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissor;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblOrdinateur;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblScore1;
    private javax.swing.JLabel lblScore2;
    // End of variables declaration//GEN-END:variables
}
